using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.DualShock;
using AutoGenerated.Input;
using BetterDebug;

namespace GameManagement.Input
{
    public class InputHandler : MonoBehaviour
    {
        [SerializeField] private PlayerController player;
        [SerializeField] private Color baseControllerColor;

        private PlayerInputActions actions;

        private void Awake()
        {
            DualShockGamepad gamepad = GetDualShock();

            if(gamepad != null)
            {
                gamepad.SetLightBarColor(baseControllerColor);
            }

            actions = new PlayerInputActions();

            actions.PlayerActions.Jump.started += Jump;
            actions.PlayerActions.Dash.started += Dash;

            EnablePlayerActionMap(actions);
        }

        private DualShockGamepad GetDualShock()
        {
            try
            {
                var gamepad = (DualShockGamepad)Gamepad.all[0];
                return gamepad;
            }
            catch
            {
                AdvancedDebug.LogError(this + " attempted to acess a DualShockGamepad object, but the array index was out of range!");
                AdvancedDebug.LogWarning("Some virtual input devices were not setup correctly, therefore your control inputs may not be read correctly!");
                return null;
            }
        }

        private void EnablePlayerActionMap(PlayerInputActions actions) { actions.PlayerActions.Enable(); }

        private void Update()
        {
            Vector2 movementVector = actions.PlayerActions.Movement.ReadValue<Vector2>();
            player.PlayerMove(movementVector);
        }

        private void Jump(InputAction.CallbackContext context)
        {
            player.PlayerJump();
        }

        private void Dash(InputAction.CallbackContext context)
        {
            player.PlayerDash();
        }
    }
}